spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wnisp?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix:classpath:/templates/

